### ISSUE TITLE
Correct Travis build failures

### ISSUE THREAD

**Issue by oskapt** [sovereign/sovereign#587]
All my commits fail CI because of some error in Travis that is unrelated to my actual code:

```
$ ansible-lint site.yml
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/travis/virtualenv/python2.7.12/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/ansiblelint/__init__.py", line 201, in run
    for file in ansiblelint.utils.find_children(arg):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/ansiblelint/utils.py", line 114, in find_children
    for child in play_children(basedir, item, playbook[1]):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/ansiblelint/utils.py", line 143, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/ansiblelint/utils.py", line 163, in _roles_children
    results.extend(_look_for_role_files(basedir, role))
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/ansiblelint/utils.py", line 196, in _look_for_role_files
    role_path = _rolepath(basedir, role)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/ansiblelint/utils.py", line 182, in _rolepath
    search_locations = C.DEFAULT_ROLES_PATH.split(os.pathsep)
AttributeError: 'list' object has no attribute 'split'
```

Can someone go buy that dude a beer so he stops crying?

**Comment by neuhaus** [comment]
wheezy is no longer supported

**Comment by oskapt** [comment]
I find these responses funny, as if wheezy support is the problem that caused you to wait 35 months before replying. Wouldn't it make more sense to close the ticket because...oh...the problem doesn't exist anymore? Something else fixed it?

If the problem still exists after 35 months and deprecating support for wheezy was the only way to fix it, then...well...wow.

At any rate, thanks for responding. Late is better than never.

**Comment by neuhaus** [comment]
Just going over some old issues. I didn't comment earlier because i has nothing to contribute.
We need more volunteers:-)

Thanks for the bug report.
