### ISSUE TITLE
Webmail role fails due to composer running as root

### ISSUE THREAD

**Issue by lukecyca** [sovereign/sovereign#604]
For testing purposes, I spun up a brand new Debian 8.6 droplet on Digital Ocean, and ran our playbook against that. The following task failed:

```
TASK [webmail : Initialize composer] *******************************************
fatal: [vps6.cycamatic.com]: FAILED! => {"changed": true, "cmd": ["php", "/root/composer.phar",
 "install", "--no-dev"], "delta": "0:01:02.753665", "end": "2016-10-18 00:19:37.924200",
 "failed": true, "rc": -9, "start": "2016-10-18 00:18:35.170535", "stderr": "Do not run Composer
 as root/super user! See https://getcomposer.org/root for details
...
```

**Comment by lukecyca** [comment]
[This wiki page](https://github.com/sovereign/sovereign/wiki/Migrating-from-Debian-7-to-Debian-8) suggests that webmail is not currently functional in the jessie branch (now master) but PR #590 has been merged and the README suggests that webmail is indeed functional.

I don't personally use webmail on my main Sovereign install. Paging @mikeashley who worked on that PR. :)

**Comment by mikeashley** [comment]
Yes, I'll take a look.

**Comment by mikeashley** [comment]
@lukecyca There are two things going on.  First, I couldn't reproduce the problem as you reported it.  The install runs clean for me.  Second, when I run the initialize task from the command line on my test server, I do get the warning reported by your Ansible run.

So I need to fix the task to not run composer as root.  That's a bug.  But I would also like to understand why my testing doesn't reproduce your report.  Can you tell me what version of Ansible you are running?  I am wondering if you are running a more paranoid deployment setup.

**Comment by mikeashley** [comment]
Took the jessie label off since jessie is mater now.  Keeping the wheezy tag for issues on that branch.

**Comment by nomadhacker** [comment]
It appears the issue is actually due to composer not allowing installs from insecure locations by default now.
https://stackoverflow.com/questions/35726742/cannot-install-horde-imap-client-with-composer

**Comment by tushartyagi** [comment]
Is there any update on this? Possibly a workaround? 
I have faced the same issue while installing sovereign on a fresh Debian 8.2 AWS instance. 

```
failed: [ip.address] => {"changed": true, "cmd": ["php", "/root/composer.phar", "install", "--no-dev"], "delta": "0:01:19.603327", "end": "2016-11-30 07:28:40.574493", "rc": -9, "start": "2016-11-30 07:27:20.971166", "warnings": []}
stderr: Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
Updating dependencies                                          

FATAL: all hosts have already failed -- aborting
```

**Comment by alexec** [comment]
+1

**Comment by mikeashley** [comment]
I am still unable to reproduce this when deploying using Ansible 2.2 to a fresh Linode test server running Debian 8.6.  That's a puzzle for me, but in the meantime, composer's documentation indicates the warning can be suppressed.  Does this patch or something similar help?

    diff --git a/roles/webmail/tasks/roundcube.yml b/roles/webmail/tasks/roundcube.y
    index 1d569ad..9e87f83 100644
    --- a/roles/webmail/tasks/roundcube.yml
    +++ b/roles/webmail/tasks/roundcube.yml
    @@ -43,6 +43,8 @@
       command: php /root/composer.phar install --no-dev
                chdir=/var/www/roundcube
                creates=/var/www/roundcube/vendor/autoload.php
    +  environment:
    +    COMPOSER_ALLOW_SUPERUSER: 1
     
     - name: Remove installer directory
       file: path=/var/www/roundcube/installer state=absent

**Comment by mikeashley** [comment]
For those who see this error, please report what version of Ansible you are using.

**Comment by Dosenpfand** [comment]
I just saw the exact same error on a Digital Ocean Server with Debian 8. The cause was that the server was running out of memory, as it only had 512 MB. When i activated a swap file the installation ran without problems.

**Comment by arpadlukacs** [comment]
ansible 2.2.1.0 here, I got the same error when trying to install stuff on a fresh Ubuntu 16.04

**Comment by Dosenpfand** [comment]
@arpadlukacs how much memory + swap did the system you tried running it on have?

**Comment by arpadlukacs** [comment]
I used VirtualBox with 2GB RAM, I'm not sure about the swap, because I just chose the automatic partition.

**Comment by cstich** [comment]
I get the same error. I am on a fresh Debiatn 8.7 and have Ansible 2.0.0.2. I do have 489MB of RAM and 511MB of swap.

I am not sure if this is helpful but I ran the playbook with `-vvvv` and I do get a slightly longer error message.

````
TASK [webmail : Initialize composer] *******************************************
task path: /home/christoph/git/sovereign/roles/webmail/tasks/roundcube.yml:42
<82.211.0.89> ESTABLISH SSH CONNECTION FOR USER: deploy
<82.211.0.89> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deploy -o ConnectTimeout=10 -o ControlPath=/home/christoph/.ansible/cp/ansible-ssh-%h-%p-%r -tt 82.211.0.89 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1488391167.49-87167567289144 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1488391167.49-87167567289144 )" )'
<82.211.0.89> PUT /tmp/tmpUkzPUk TO /home/deploy/.ansible/tmp/ansible-tmp-1488391167.49-87167567289144/command
<82.211.0.89> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deploy -o ConnectTimeout=10 -o ControlPath=/home/christoph/.ansible/cp/ansible-ssh-%h-%p-%r '[82.211.0.89]'
<82.211.0.89> ESTABLISH SSH CONNECTION FOR USER: deploy
<82.211.0.89> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deploy -o ConnectTimeout=10 -o ControlPath=/home/christoph/.ansible/cp/ansible-ssh-%h-%p-%r -tt 82.211.0.89 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gldnqcwzufnrzmqavljiqtieccxktlit; LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /home/deploy/.ansible/tmp/ansible-tmp-1488391167.49-87167567289144/command; rm -rf "/home/deploy/.ansible/tmp/ansible-tmp-1488391167.49-87167567289144/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
fatal: [82.211.0.89]: FAILED! => {"changed": true, "cmd": ["php", "/root/composer.phar", "install", "--no-dev"], "delta": "0:00:29.110692", "end": "2017-03-01 18:59:57.418199", "failed": true, "invocation": {"module_args": {"_raw_params": "php /root/composer.phar install --no-dev", "_uses_shell": false, "chdir": "/var/www/roundcube", "creates": "/var/www/roundcube/vendor/autoload.php", "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 2, "start": "2017-03-01 18:59:28.307507", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nInitializing PEAR repository https://pear.php.net\nPEAR repository from https://pear.php.net could not be loaded. Undefined index: channel\n\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (RELEASE_1_1_6)                           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (RELEASE_1_1_5)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (RELEASE_1_1_3)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (RELEASE_1_1_2)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (RELEASE_1_0_4)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (RELEASE_0_8_1)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (RELEASE_0_8)  \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (Net_Sieve-1.5.0)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (Net_Sieve-1.3.3)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (Net_Sieve-1.3.2)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (Net_Sieve-1.3.1)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (Net_Sieve-1.3.0)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (Net_Sieve-1.2.1)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (Net_Sieve-1.2.0)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (1.5.3)          \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (1.5.2)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (1.5.1)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (1.5.0)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b                                                    \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of roundcube/net_sieve (master)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b                                                     \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of kolab/net_ldap3 (pear-Net-LDAP3-1.0.0)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of kolab/net_ldap3 (pear-Net-LDAP3-1.0.1)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of kolab/net_ldap3 (pear-Net-LDAP3-1.0.2)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of kolab/net_ldap3 (pear-Net-LDAP3-1.0.3)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of kolab/net_ldap3 (pear-Net-LDAP3-1.0.4)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of kolab/net_ldap3 (pear-Net-LDAP3-1.0.5)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b                                                               \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bReading composer.json of kolab/net_ldap3 (master)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b                                                 \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bUpdating dependencies\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - The requested package pear-pear.php.net/net_socket could not be found in any version, there may be a typo in the package name.\n  Problem 2\n    - The requested package pear-pear.php.net/auth_sasl could not be found in any version, there may be a typo in the package name.\n  Problem 3\n    - The requested package pear-pear.php.net/net_idna2 could not be found in any version, there may be a typo in the package name.\n  Problem 4\n    - The requested package pear-pear.php.net/mail_mime could not be found in any version, there may be a typo in the package name.\n  Problem 5\n    - The requested package pear-pear.php.net/net_smtp could not be found in any version, there may be a typo in the package name.\n  Problem 6\n    - The requested package pear-pear.php.net/crypt_gpg could not be found in any version, there may be a typo in the package name.\n\nPotential causes:\n - A typo in the package name\n - The package is not available in a stable-enough version according to your minimum-stability setting\n   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.\n\nRead <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.", "stdout": "", "stdout_lines": [], "warnings": []}
````



`

**Comment by cstich** [comment]
I did some digging around and apparently there seems to be bug somewhere upstream with regards to `composer` and the `PEARL` repository. The same issue is referenced at Roundcube [here](https://github.com/composer/composer/issues/6193) as well.

**Comment by mikeashley** [comment]
Issue #659 points out that Roundcube has updated their install to work around the problem.  An updated  configuration is included in the issue.  If somebody could verify the fix and submit a pull request, that would be great.

**Comment by sauravg** [comment]
The issue with Pear/Roundcube is gone. But if people are stuck at a failed run due to that reason, they'd need to delete /tmp/composer-installer and /root/composer.phar to proceed.

So may be a patch could be as below, but I haven't tested it and I don't know ansible, so it might not be as simple as this
`
diff --git a/roles/webmail/tasks/roundcube.yml b/roles/webmail/tasks/roundcube.yml
index 1d569ad..f6db8c2 100644
--- a/roles/webmail/tasks/roundcube.yml
+++ b/roles/webmail/tasks/roundcube.yml
@@ -27,6 +27,7 @@
 - name: Get Composer installer
   get_url: url=https://getcomposer.org/installer
            dest=/tmp/composer-installer
+           force=yes
 
 - name: Copy composer configuration
   copy: src=var_www_roundcube_composer.json dest=/var/www/roundcube/composer.json
`

**Comment by robinfehr** [comment]
i tried your workarounds - now the  at the "initialize composer" task it does not continue...
does anyone have some other workarounds?

**Comment by lrettig** [comment]
Getting this now on a fresh Debian 9.12 system. ansible is `ansible 2.9.6, python version = 3.7.7`

```
TASK [webmail : Initialize composer] **********************************************************************************
fatal: [35.230.171.34]: FAILED! => {"changed": true, "cmd": ["php", "/root/composer.phar", "install", "--no-dev"], "delta": "0:00:00.164040", "end": "2020-04-07 19:10:25.932851", "msg": "non-zero return code", "rc": 255, "start": "2020-04-07 19:10:25.768811", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nInitializing PEAR repository https://pear.php.net\nPHP Fatal error:  Uncaught Error: Call to undefined function Composer\\Repository\\Pear\\simplexml_load_string() in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php:74\nStack trace:\n#0 phar:///root/composer.phar/src/Composer/Repository/Pear/ChannelReader.php(53): Composer\\Repository\\Pear\\BaseChannelReader->requestXml('https://pear.ph...', '/channel.xml')\n#1 phar:///root/composer.phar/src/Composer/Repository/PearRepository.php(83): Composer\\Repository\\Pear\\ChannelReader->read('https://pear.ph...')\n#2 phar:///root/composer.phar/src/Composer/Repository/ArrayRepository.php(195): Composer\\Repository\\PearRepository->initialize()\n#3 phar:///root/composer.phar/src/Composer/DependencyResolver/Pool.php(104): Composer\\Repository\\ArrayRepository->getPackages()\n#4 phar:///root/composer.phar/src/Composer/Installer.php(393): Composer\\DependencyResolver\\Pool->addRepository(Object(Composer\\Repository\\PearRepository), Array)\n#5 phar:///root/composer.phar/src/Composer/Installer.php(232): Composer\\Installer->doInstall(Obj in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php on line 74", "stderr_lines": ["Do not run Composer as root/super user! See https://getcomposer.org/root for details", "Loading composer repositories with package information", "Initializing PEAR repository https://pear.php.net", "PHP Fatal error:  Uncaught Error: Call to undefined function Composer\\Repository\\Pear\\simplexml_load_string() in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php:74", "Stack trace:", "#0 phar:///root/composer.phar/src/Composer/Repository/Pear/ChannelReader.php(53): Composer\\Repository\\Pear\\BaseChannelReader->requestXml('https://pear.ph...', '/channel.xml')", "#1 phar:///root/composer.phar/src/Composer/Repository/PearRepository.php(83): Composer\\Repository\\Pear\\ChannelReader->read('https://pear.ph...')", "#2 phar:///root/composer.phar/src/Composer/Repository/ArrayRepository.php(195): Composer\\Repository\\PearRepository->initialize()", "#3 phar:///root/composer.phar/src/Composer/DependencyResolver/Pool.php(104): Composer\\Repository\\ArrayRepository->getPackages()", "#4 phar:///root/composer.phar/src/Composer/Installer.php(393): Composer\\DependencyResolver\\Pool->addRepository(Object(Composer\\Repository\\PearRepository), Array)", "#5 phar:///root/composer.phar/src/Composer/Installer.php(232): Composer\\Installer->doInstall(Obj in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php on line 74"], "stdout": "\nFatal error: Uncaught Error: Call to undefined function Composer\\Repository\\Pear\\simplexml_load_string() in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php:74\nStack trace:\n#0 phar:///root/composer.phar/src/Composer/Repository/Pear/ChannelReader.php(53): Composer\\Repository\\Pear\\BaseChannelReader->requestXml('https://pear.ph...', '/channel.xml')\n#1 phar:///root/composer.phar/src/Composer/Repository/PearRepository.php(83): Composer\\Repository\\Pear\\ChannelReader->read('https://pear.ph...')\n#2 phar:///root/composer.phar/src/Composer/Repository/ArrayRepository.php(195): Composer\\Repository\\PearRepository->initialize()\n#3 phar:///root/composer.phar/src/Composer/DependencyResolver/Pool.php(104): Composer\\Repository\\ArrayRepository->getPackages()\n#4 phar:///root/composer.phar/src/Composer/Installer.php(393): Composer\\DependencyResolver\\Pool->addRepository(Object(Composer\\Repository\\PearRepository), Array)\n#5 phar:///root/composer.phar/src/Composer/Installer.php(232): Composer\\Installer->doInstall(Obj in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php on line 74", "stdout_lines": ["", "Fatal error: Uncaught Error: Call to undefined function Composer\\Repository\\Pear\\simplexml_load_string() in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php:74", "Stack trace:", "#0 phar:///root/composer.phar/src/Composer/Repository/Pear/ChannelReader.php(53): Composer\\Repository\\Pear\\BaseChannelReader->requestXml('https://pear.ph...', '/channel.xml')", "#1 phar:///root/composer.phar/src/Composer/Repository/PearRepository.php(83): Composer\\Repository\\Pear\\ChannelReader->read('https://pear.ph...')", "#2 phar:///root/composer.phar/src/Composer/Repository/ArrayRepository.php(195): Composer\\Repository\\PearRepository->initialize()", "#3 phar:///root/composer.phar/src/Composer/DependencyResolver/Pool.php(104): Composer\\Repository\\ArrayRepository->getPackages()", "#4 phar:///root/composer.phar/src/Composer/Installer.php(393): Composer\\DependencyResolver\\Pool->addRepository(Object(Composer\\Repository\\PearRepository), Array)", "#5 phar:///root/composer.phar/src/Composer/Installer.php(232): Composer\\Installer->doInstall(Obj in phar:///root/composer.phar/src/Composer/Repository/Pear/BaseChannelReader.php on line 74"]}
```
